# -*- coding: utf-8 -*-
"""A2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L8OBCWufxtmDpkiNTq-VE7r6RjbzoAh7
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# ----------------------------
# Load Iris dataset
# ----------------------------
iris = load_iris()
X_all = iris.data
y_all = iris.target

# Keep only Setosa (0) and Versicolor (1)
mask = y_all < 2
X_all = X_all[mask]
y_all = y_all[mask]

# Select features: Sepal Length (0) and Petal Length (2)
X = X_all[:, [0, 2]]
T = y_all

# Convert labels to {-1, +1}
T = np.where(T == 0, -1, 1)


# ----------------------------
# Rosenblatt Perceptron
# ----------------------------
class Perceptron:
    def __init__(self, lr=1.0, epochs=100):
        self.lr = lr
        self.epochs = epochs
        self.w = None

    def fit(self, X, y):
        n, d = X.shape
        Xb = np.c_[np.ones(n), X]  # add bias term
        self.w = np.zeros(d + 1)

        mistakes_per_epoch = []

        for epoch in range(self.epochs):
            mistakes = 0
            for xi, yi in zip(Xb, y):
                if yi * np.dot(self.w, xi) <= 0:
                    self.w += self.lr * yi * xi
                    mistakes += 1
            mistakes_per_epoch.append(mistakes)

            if mistakes == 0:
                break

        return mistakes_per_epoch

    def predict(self, X):
        Xb = np.c_[np.ones(X.shape[0]), X]
        return np.sign(Xb @ self.w)


# ----------------------------
# Train
# ----------------------------
model = Perceptron(lr=1.0, epochs=100)
mistakes = model.fit(X, T)

print("Final weights (bias, w1, w2):", model.w)
print("Epochs used:", len(mistakes))
print("Final mistakes:", mistakes[-1])


# ----------------------------
# Plot data + decision boundary
# ----------------------------
plt.scatter(X[T == -1][:, 0], X[T == -1][:, 1], label="Setosa")
plt.scatter(X[T == 1][:, 0], X[T == 1][:, 1], label="Versicolor")

# Decision boundary
w0, w1, w2 = model.w
x_vals = np.linspace(X[:,0].min(), X[:,0].max(), 100)
y_vals = -(w0 + w1*x_vals) / w2
plt.plot(x_vals, y_vals)

plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Perceptron: Setosa vs Versicolor")
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# ----------------------------
# Load Iris dataset
# ----------------------------
iris = load_iris()
X_all = iris.data
y_all = iris.target

# Keep only Setosa (0) and Versicolor (1)
mask = y_all < 2
X_all = X_all[mask]
y_all = y_all[mask]

# Select features: Sepal Length (0) and Petal Length (2)
X = X_all[:, [1, 3]]
T = y_all

# Convert labels to {-1, +1}
T = np.where(T == 0, -1, 1)


# ----------------------------
# Rosenblatt Perceptron
# ----------------------------
class Perceptron:
    def __init__(self, lr=1.0, epochs=100):
        self.lr = lr
        self.epochs = epochs
        self.w = None

    def fit(self, X, y):
        n, d = X.shape
        Xb = np.c_[np.ones(n), X]  # add bias term
        self.w = np.zeros(d + 1)

        mistakes_per_epoch = []

        for epoch in range(self.epochs):
            mistakes = 0
            for xi, yi in zip(Xb, y):
                if yi * np.dot(self.w, xi) <= 0:
                    self.w += self.lr * yi * xi
                    mistakes += 1
            mistakes_per_epoch.append(mistakes)

            if mistakes == 0:
                break

        return mistakes_per_epoch

    def predict(self, X):
        Xb = np.c_[np.ones(X.shape[0]), X]
        return np.sign(Xb @ self.w)


# ----------------------------
# Train
# ----------------------------
model = Perceptron(lr=1.0, epochs=100)
mistakes = model.fit(X, T)

print("Final weights (bias, w1, w2):", model.w)
print("Epochs used:", len(mistakes))
print("Final mistakes:", mistakes[-1])
print("Training accuracy:", np.mean(model.predict(X) == T))


# ----------------------------
# Plot data + decision boundary
# ----------------------------
plt.scatter(X[T == -1][:, 0], X[T == -1][:, 1], label="Setosa")
plt.scatter(X[T == 1][:, 0], X[T == 1][:, 1], label="Versicolor")

# Decision boundary
w0, w1, w2 = model.w
x_vals = np.linspace(X[:,0].min(), X[:,0].max(), 100)
y_vals = -(w0 + w1*x_vals) / w2
plt.plot(x_vals, y_vals)

plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.title("Part(b): Perceptron on Iris(Sepal Width vs Petal Width)")
plt.legend()
plt.show()

