# -*- coding: utf-8 -*-
"""Assignement3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsXkhBHoZVtYzKtg6U0mk8Vvp0unlHdN
"""

import csv
import math
import random


try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None


# ========= ADDED  =========
try:
    import pandas as pd
except ImportError:
    pd = None
# ==========================================


# ========= CHANGED  =========
CSV_PATH = "/content/Titanic.csv"
# =========================================================================

RANDOM_SEED = 2026
TEST_SIZE = 0.30
EPOCHS = 400
LEARNING_RATE = 0.10

# ========= ADDED  =========
RUN_BONUS = False   # keep Part B code in the file, but don't run it for Part A
# ==============================================


def accuracy_score(y_true, y_pred):
    correct = sum(1 for actual, predicted in zip(y_true, y_pred) if actual == predicted)
    return correct / len(y_true)


def confusion_matrix(y_true, y_pred):
    tn = fp = fn = tp = 0
    for actual, predicted in zip(y_true, y_pred):
        if actual == 0 and predicted == 0:
            tn += 1
        elif actual == 0 and predicted == 1:
            fp += 1
        elif actual == 1 and predicted == 0:
            fn += 1
        else:
            tp += 1
    return [[tn, fp], [fn, tp]]


def load_titanic_data(csv_path):
    class_map = {"1st": 1.0, "2nd": 2.0, "3rd": 3.0, "crew": 4.0}
    sex_map = {"male": 0.0, "female": 1.0}
    age_map = {"adult": 0.0, "child": 1.0}
    survived_map = {"no": 0, "yes": 1}

    features = []
    targets = []

    with open(csv_path, newline="", encoding="utf-8-sig") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            passenger_class = class_map[row["Class"].strip().lower()]
            sex = sex_map[row["Sex"].strip().lower()]
            age = age_map[row["Age"].strip().lower()]
            survived = survived_map[row["Survived"].strip().lower()]

            features.append([passenger_class, sex, age])
            targets.append(survived)

    return features, targets


# ========= ADDED  =========
def load_titanic_data_pandas(csv_path):
    """
    Same output format as load_titanic_data(): (features, targets)
    Uses pandas if available, but your original CSV-based function stays.
    """
    class_map = {"1st": 1.0, "2nd": 2.0, "3rd": 3.0, "crew": 4.0}
    sex_map = {"male": 0.0, "female": 1.0}
    age_map = {"adult": 0.0, "child": 1.0}
    survived_map = {"no": 0, "yes": 1}

    df = pd.read_csv(csv_path)

    # normalize strings
    df["Class"] = df["Class"].astype(str).str.strip().str.lower()
    df["Sex"] = df["Sex"].astype(str).str.strip().str.lower()
    df["Age"] = df["Age"].astype(str).str.strip().str.lower()
    df["Survived"] = df["Survived"].astype(str).str.strip().str.lower()

    features = []
    targets = []

    for _, row in df.iterrows():
        passenger_class = class_map[row["Class"]]
        sex = sex_map[row["Sex"]]
        age = age_map[row["Age"]]
        survived = survived_map[row["Survived"]]

        features.append([passenger_class, sex, age])
        targets.append(survived)

    return features, targets
# ========================================================================


def stratified_train_test_split(features, targets, test_size, seed):
    rng = random.Random(seed)
    grouped_indices = {0: [], 1: []}

    for index, target in enumerate(targets):
        grouped_indices[target].append(index)

    train_indices = []
    test_indices = []

    for label, indices in grouped_indices.items():
        rng.shuffle(indices)
        split_index = int(len(indices) * (1.0 - test_size))
        split_index = max(1, min(split_index, len(indices) - 1))
        train_indices.extend(indices[:split_index])
        test_indices.extend(indices[split_index:])

    rng.shuffle(train_indices)
    rng.shuffle(test_indices)

    x_train = [features[index] for index in train_indices]
    x_test = [features[index] for index in test_indices]
    y_train = [targets[index] for index in train_indices]
    y_test = [targets[index] for index in test_indices]
    return x_train, x_test, y_train, y_test


def fit_standard_scaler(train_features, test_features):
    column_count = len(train_features[0])
    means = []
    stds = []

    for column in range(column_count):
        values = [row[column] for row in train_features]
        mean_value = sum(values) / len(values)
        variance = sum((value - mean_value) ** 2 for value in values) / len(values)
        std_value = math.sqrt(variance)
        if std_value == 0.0:
            std_value = 1.0
        means.append(mean_value)
        stds.append(std_value)

    def transform(rows):
        scaled_rows = []
        for row in rows:
            scaled_rows.append(
                [(value - means[index]) / stds[index] for index, value in enumerate(row)]
            )
        return scaled_rows

    return transform(train_features), transform(test_features)


def sigmoid(value):
    value = max(min(value, 500.0), -500.0)
    return 1.0 / (1.0 + math.exp(-value))


class NeuralNetwork:
    def __init__(self, input_size, hidden_layers, learning_rate, seed):
        layer_sizes = [input_size] + hidden_layers + [1]
        self.learning_rate = learning_rate
        self.rng = random.Random(seed)
        self.weights = []
        self.biases = []

        for start_size, end_size in zip(layer_sizes[:-1], layer_sizes[1:]):
            limit = 1.0 / math.sqrt(start_size)
            layer_weights = []
            for _ in range(end_size):
                layer_weights.append(
                    [self.rng.uniform(-limit, limit) for _ in range(start_size)]
                )
            layer_biases = [self.rng.uniform(-limit, limit) for _ in range(end_size)]
            self.weights.append(layer_weights)
            self.biases.append(layer_biases)

    def forward(self, inputs):
        activations = [inputs[:]]
        zs = []
        current = inputs[:]

        for layer_weights, layer_biases in zip(self.weights, self.biases):
            z_values = []
            next_values = []
            for neuron_weights, neuron_bias in zip(layer_weights, layer_biases):
                weighted_sum = sum(
                    weight * value for weight, value in zip(neuron_weights, current)
                ) + neuron_bias
                z_values.append(weighted_sum)
                next_values.append(sigmoid(weighted_sum))
            zs.append(z_values)
            activations.append(next_values)
            current = next_values

        return activations, zs

    def backward(self, activations, target):
        deltas = [None] * len(self.weights)
        output = activations[-1][0]
        deltas[-1] = [(output - target) * output * (1.0 - output)]

        for layer_index in range(len(self.weights) - 2, -1, -1):
            layer_deltas = []
            for neuron_index in range(len(self.weights[layer_index])):
                downstream = 0.0
                for next_neuron_index in range(len(self.weights[layer_index + 1])):
                    downstream += (
                        self.weights[layer_index + 1][next_neuron_index][neuron_index]
                        * deltas[layer_index + 1][next_neuron_index]
                    )
                activation = activations[layer_index + 1][neuron_index]
                layer_deltas.append(downstream * activation * (1.0 - activation))
            deltas[layer_index] = layer_deltas

        for layer_index in range(len(self.weights)):
            inputs = activations[layer_index]
            for neuron_index in range(len(self.weights[layer_index])):
                for weight_index in range(len(self.weights[layer_index][neuron_index])):
                    self.weights[layer_index][neuron_index][weight_index] -= (
                        self.learning_rate
                        * deltas[layer_index][neuron_index]
                        * inputs[weight_index]
                    )
                self.biases[layer_index][neuron_index] -= (
                    self.learning_rate * deltas[layer_index][neuron_index]
                )

    def train(self, training_features, training_targets, epochs):
        errors = []

        for _ in range(epochs):
            total_error = 0.0
            for inputs, target in zip(training_features, training_targets):
                activations, _ = self.forward(inputs)
                prediction = activations[-1][0]
                total_error += (target - prediction) ** 2
                self.backward(activations, target)
            errors.append(total_error / len(training_features))

        return errors

    def predict_probability(self, inputs):
        activations, _ = self.forward(inputs)
        return activations[-1][0]

    def predict(self, rows):
        predictions = []
        for row in rows:
            probability = self.predict_probability(row)
            predictions.append(1 if probability >= 0.5 else 0)
        return predictions


def print_results(title, y_train, train_predictions, y_test, test_predictions):
    train_accuracy = accuracy_score(y_train, train_predictions)
    test_accuracy = accuracy_score(y_test, test_predictions)

    print(title)
    print("Training accuracy:", round(train_accuracy, 4))
    print("Test accuracy:", round(test_accuracy, 4))
    print("Training confusion matrix:", confusion_matrix(y_train, train_predictions))
    print("Test confusion matrix:", confusion_matrix(y_test, test_predictions))
    print()


def plot_errors(error_history, title):
    if plt is None:
        print(f"{title} error history skipped because matplotlib is not installed.")
        return

    plt.figure()
    plt.plot(range(1, len(error_history) + 1), error_history)
    plt.title(title)
    plt.xlabel("Epoch")
    plt.ylabel("Mean Squared Error")
    plt.grid(True)


def main():
    random.seed(RANDOM_SEED)

    # ========= ADDED  =========
    if pd is not None:
        features, targets = load_titanic_data_pandas(CSV_PATH)
    else:
        features, targets = load_titanic_data(CSV_PATH)
    # =====================================================================================

    x_train, x_test, y_train, y_test = stratified_train_test_split(
        features, targets, TEST_SIZE, RANDOM_SEED
    )
    x_train, x_test = fit_standard_scaler(x_train, x_test)

    print("Dataset size:", len(features))
    print("Training rows:", len(x_train))
    print("Test rows:", len(x_test))
    print("Input feature count:", len(x_train[0]))
    print()

    # Part A: 1 hidden layer, 2 nodes
    two_node_nn = NeuralNetwork(
        input_size=len(x_train[0]),
        hidden_layers=[2],
        learning_rate=LEARNING_RATE,
        seed=RANDOM_SEED,
    )
    two_node_errors = two_node_nn.train(x_train, y_train, EPOCHS)
    two_node_train_predictions = two_node_nn.predict(x_train)
    two_node_test_predictions = two_node_nn.predict(x_test)
    print_results(
        "Part A: 1 hidden layer with 2 nodes",
        y_train,
        two_node_train_predictions,
        y_test,
        two_node_test_predictions,
    )
    plot_errors(two_node_errors, "2-node network error")

    # ===================== Part B (Bonus) =====================
    # 2 hidden layers, 2 nodes each (total 4 hidden nodes)

    four_node_nn = NeuralNetwork(
        input_size=len(x_train[0]),
        hidden_layers=[2, 2],   # two hidden layers, 2 nodes each
        learning_rate=LEARNING_RATE,
        seed=RANDOM_SEED,
    )

    four_node_errors = four_node_nn.train(x_train, y_train, EPOCHS)

    four_node_train_predictions = four_node_nn.predict(x_train)
    four_node_test_predictions = four_node_nn.predict(x_test)

    print("Part B: 2 hidden layers with 2 nodes each")
    print("Training accuracy:", round(accuracy_score(y_train, four_node_train_predictions), 4))
    print("Test accuracy:", round(accuracy_score(y_test, four_node_test_predictions), 4))
    print("Training confusion matrix:", confusion_matrix(y_train, four_node_train_predictions))
    print("Test confusion matrix:", confusion_matrix(y_test, four_node_test_predictions))
    print()

    plot_errors(four_node_errors, "4-node (2x2) network error")
    # ==========================================================