# -*- coding: utf-8 -*-
"""a3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsXkhBHoZVtYzKtg6U0mk8Vvp0unlHdN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler

# Load Titanic data
titanic = pd.read_csv("Titanic.csv")
print(titanic.head())

# Input X and target y
X = titanic[["Class", "Sex", "Age"]].copy()
y = titanic["Survived"].copy()

# Convert categorical values to numbers
X["Class"] = X["Class"].replace({
    "1st": 1,
    "2nd": 2,
    "3rd": 3,
    "Crew": 4
})

X["Sex"] = X["Sex"].replace({
    "Male": 0,
    "Female": 1
})

X["Age"] = X["Age"].replace({
    "Adult": 0,
    "Child": 1
})

y = y.replace({
    "No": 0,
    "Yes": 1
})

print(X.shape)
print(y.shape)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=5
)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =========================
# Part A: 1 hidden layer with 2 nodes
# =========================
mlp_a = MLPClassifier(
    hidden_layer_sizes=(2,),
    activation="logistic",
    max_iter=1000,
    random_state=2022,
    learning_rate_init=0.01,
    verbose=True
)

mlp_a.fit(X_train, y_train)

plt.plot(mlp_a.loss_curve_)
plt.title("Training Error for Part A")
plt.xlabel("Iteration")
plt.ylabel("Loss")
plt.show()

y_train_pred_a = mlp_a.predict(X_train)
y_test_pred_a = mlp_a.predict(X_test)

print("Part A: 1 hidden layer with 2 nodes")
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_a))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred_a))
print("Training Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred_a))
print("Test Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_a))

cm_a = confusion_matrix(y_test, y_test_pred_a)
ConfusionMatrixDisplay(confusion_matrix=cm_a).plot()
plt.title("Part A Test Confusion Matrix")
plt.show()

# =========================
# Part B: 2 hidden layers with 2 nodes each
# =========================
mlp_b = MLPClassifier(
    hidden_layer_sizes=(2, 2),
    activation="logistic",
    max_iter=1000,
    random_state=2022,
    learning_rate_init=0.01,
    verbose=True
)

mlp_b.fit(X_train, y_train)

plt.plot(mlp_b.loss_curve_)
plt.title("Training Error for Part B")
plt.xlabel("Iteration")
plt.ylabel("Loss")
plt.show()

y_train_pred_b = mlp_b.predict(X_train)
y_test_pred_b = mlp_b.predict(X_test)

print("Part B: 2 hidden layers with 2 nodes each")
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_b))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred_b))
print("Training Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred_b))
print("Test Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_b))

cm_b = confusion_matrix(y_test, y_test_pred_b)
ConfusionMatrixDisplay(confusion_matrix=cm_b).plot()
plt.title("Part B Test Confusion Matrix")
plt.show()

